version: '3'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - HOST=0.0.0.0

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge