version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: DokerFile
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: DokerFile
    ports:
      - "80:80"
